BoxLayout:
    orientation: 'vertical'
    Button:
        id: my_button1
        text: "Cheese"
        on_press: app.on_button_press(self)
    Button:
        id: my_button2
        text: "Laptop"
        on_press: app.on_button_press(self)

    Button:
        id: my_button3
        text:"Plant"
        on_press:app.on_button_press(self)

    BoxLayout:
        size_hint_max_y:200
        Label:
            id: price_label
            text:"Total Price: $0"
        Button:
            id: "reset_button"
            on_press: app.on_reset_press(self)
            text: 'Reset'

